name: MortgageAnalytics
description: ''
version: 1.0.5
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: mortgageanalytics
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-12 18:55:42'
pipelines:
  pipelines/mortgage_analytics:
    name: mortgage_analytics
    description: This codebase provides a mortgage analysis pipeline that processes
      data from two CSV files, MortgageEast.csv and MortgageWest.csv. The data is
      cleaned and merged, and then various calculations are performed to identify
      troubled mortgages. The troubled mortgages are then aggregated by state and
      sorted by the number of properties in trouble. Finally, the results are saved
      to a Delta table and a CSV file for further analysis and reporting.
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-12 18:55:42'
    datasets:
      inputs:
      - datasets/mortgage_east
      - datasets/mortgage_west
      outputs:
      - datasets/state_analysis_csv
      - datasets/tar_all_mortgages
      - datasets/tar_troubled_mortgages
    subgraphs: []
    dependencies: {}
  pipelines/troubled_mortgage_assistance:
    name: troubled_mortgage_HAF
    description: This codebase provides a mortgage assistance program that helps identify
      troubled mortgages in Nevada and provides assistance to customers. It reads
      in data from two sources, the `troubled_mortgages` table and the `MortgageCustomerNV.csv`
      file, and filters the customer data to only include those in Nevada. It then
      reformats the account number and joins the customer data with the mortgage data
      to create a comprehensive view of the customer's mortgage information. Finally,
      it writes the output to a CSV file named `mtg_assist_program.csv`. This program
      could be used by mortgage companies to identify and assist customers who are
      struggling with their mortgage payments.
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-13 14:45:58'
    datasets:
      inputs:
      - datasets/customers_nv
      - datasets/tar_troubled_mortgages
      outputs:
      - datasets/myg_assist_program_csv
    subgraphs: []
    dependencies: {}
datasets:
  datasets/mortgage_east:
    name: mortgage_east
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 18:58:23'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 18:58:23'
  datasets/mortgage_west:
    name: mortgage_west
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 19:01:16'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 19:01:16'
  datasets/tar_all_mortgages:
    name: tar_all_mortgages
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:17:44'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:17:44'
  datasets/customers_nv:
    name: customers_nv
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:37:42'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:37:42'
  datasets/state_analysis_csv:
    name: state_analysis_csv
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:51:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:51:58'
  datasets/myg_assist_program_csv:
    name: myg_assist_program_csv
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:56:10'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:56:10'
  datasets/tar_troubled_mortgages:
    name: tar_troubled_mortgages
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-13 14:49:32'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-13 14:49:32'
templates: {}
jobs:
  jobs/job_MortgageAnalytics_DBX:
    name: job_MortgageAnalytics_DBX
    description: ''
    fabricUID: 9631
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/mortgage_analytics
    - pipelines/troubled_mortgage_assistance
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-03-13 18:48:01'
    author: bobw@prophecy.io
  jobs/job_MortgageAnalytics_AF:
    name: job_MortgageAnalytics_AF
    description: ''
    fabricUID: 9770
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-03-13 18:49:09'
    author: bobw@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-12 18:55:42'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-08T16:46:12.899048Z'
  name: plibMaven
  version: 7.1.97
  id: '2077761997'
  createdAt: '2024-05-08T16:46:12.89889Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-05-08T16:46:12.899101Z'
  name: plibPypi
  version: 1.8.19
  id: '694918790'
  createdAt: '2024-05-08T16:46:12.899086Z'
  enabled: true
  entity: Project
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-21 15:48:59'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-21 15:49:02'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
