name: MortgageAnalytics
description: ''
version: 0.0.1
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: mortgageanalytics
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-12 18:55:42'
pipelines:
  pipelines/mortgage_analytics:
    name: mortgage_analytics
    description: ''
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-12 18:55:42'
    datasets:
      inputs:
      - datasets/mortgage_east
      - datasets/mortgage_west
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/mortgage_east:
    name: mortgage_east
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 18:58:23'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 18:58:23'
  datasets/mortgage_west:
    name: mortgage_west
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 19:01:16'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 19:01:16'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-12 18:55:42'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-12 18:55:20'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-12 18:55:20'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
